name: 🧐 Check
run-name: "Checking `${{ github.head_ref || github.ref_name }}`"

on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
  workflow_call:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  NODE_VERSION: ${{ vars.NODE_VERSION}}

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: 𐂷 Checkout
        uses: actions/checkout@v4
        with:
          repository: dgrebb/dboard
          ref: ${{ github.ref }}
          token: ${{ github.token }}
          fetch-depth: 1

      - name: 🛢 Install & Cache Dependencies
        uses: ./.github/actions/cache-deps
        with:
          NODE_VERSION: ${{ vars.NODE_VERSION}}
          PNPM_VERSION: ${{ vars.PNPM_VERSION}}

      - name: "`pnpm check`"
        continue-on-error: true
        run: pnpm check
