name: 🧐 Check
run-name: "Checking `${{ github.head_ref || github.ref_name }}`"

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]
  workflow_dispatch:
  workflow_call:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  NODE_VERSION: ${{ vars.NODE_VERSION}}

jobs:
  check:
    name: 🧐 Check
    runs-on: ubuntu-latest

    steps:
      - name: 𐂷 Checkout
        uses: actions/checkout@v4
        with:
          repository: dgrebb/dboard
          ref: ${{ github.head_ref }}
          token: ${{ github.token }}
          fetch-depth: 1

      - name: 🛢 Install & Cache Dependencies
        uses: ./.github/actions/cache-deps
        with:
          NODE_VERSION: ${{ vars.NODE_VERSION}}
          PNPM_VERSION: ${{ vars.PNPM_VERSION}}

      - name: 🎛️ Environment Configuration
        uses: ./.github/actions/set-env
        with:
          SECRET_NIGHTSCOUT_TOKEN: ${{ secrets.SECRET_NIGHTSCOUT_TOKEN }}
          PUBLIC_HUE_USERNAME: ${{ secrets.PUBLIC_HUE_USERNAME }}
          SECRET_NEST_CLIENT: ${{ secrets.SECRET_NEST_CLIENT }}
          SECRET_NEST_CLIENT_SECRET: ${{ secrets.SECRET_NEST_CLIENT_SECRET }}
          SECRET_AUDIO_CONTROL_IP_ADDRESS: ${{ secrets.SECRET_AUDIO_CONTROL_IP_ADDRESS }}
          SECRET_WIIM_SOAP_API_PORT: ${{ secrets.SECRET_WIIM_SOAP_API_PORT }}
          PUBLIC_HOST_URL: ${{ secrets.PUBLIC_HOST_URL }}

      - name: 🧐 Check
        run: pnpm check
