name: 🤖 Auto-Release
run-name: "🔖 Analyzing Release"

on:
  # push:
  #   branches: [release/*]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: "Creating release from `${{ github.ref_name }}`"
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          target-branch: ${{ github.ref_name }}
          token: ${{ secrets.GH_TOKEN }}
          config-file: .config/release/config.json
          manifest-file: .config/release/.manifest.json
          skip-github-release: true
