name: 🔀 Release PR
run-name: "${{ steps.release.outputs.prs_created && 'Created' || 'Creating' }} Release PR from `${{ github.head_ref || github.ref_name }}`"

on:
  push:
    branches: [release/*]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: "${{ steps.release.outputs.prs_created && 'Generated' || 'Generating' }} `CHANGELOG` and PR for `${{ github.head_ref || github.ref_name }}`"
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GH_TOKEN }}
          config-file: .config/release/config.json
          manifest-file: .config/release/.manifest.json
          skip-github-release: true
