name: 🚥 Release PR
run-name: "🔖 Create release PR from `${{ github.head_ref || github.ref_name }}`."

on:
  push:
    branches: [release/*]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: "🔖 Evaluating Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run release-please-action
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GH_TOKEN }}
          config-file: .config/release/config.json
          manifest-file: .config/release/.manifest.json
          skip-github-release: true
