name: Release
run-name: "Release`${{ github.head_ref || github.ref_name }}`"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          token: ${{ secrets.GH_TOKEN }}
          config-file: .config/release/config.json
          manifest-file: .config/release/.manifest.json
          target-branch: main
          draft: true
          draft-pull-request: true
          release-label: "autorelease: tagged, RELEASE"
          include-component-in-tag: false
