name: 🚥 Release
run-name: "Releasing `${{ github.head_ref || github.ref_name }}`"

on:
  push:
    branches: [release/*]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: "Generating release notes and PR for `${{ github.head_ref || github.ref_name }}`"
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          token: ${{ secrets.GH_TOKEN }}
          config-file: .config/release/config.json
          manifest-file: .config/release/.manifest.json
          target-branch: main
          include-component-in-tag: false
